name: fork-sync

on:
  push:
    branches:
      -main
  schedule:
    - cron: 6 */12 * * *
jobs:
  update_external_airflow_fork:
    runs-on: ubuntu-latest
    steps:
      - uses: TobKed/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          upstream_repository: JDHelloWorld/jd_scripts
          target_repository: kudou61/jd_scripts_hello
          upstream_branch: main
          target_branch: main
          force: true
          tags: true
